from pathlib import Path

raw_backend = """¿Por qué se eligió Spring WebFlux para el backend y qué beneficio aporta este stack?|El backend declara la dependencia org.springframework.boot:spring-boot-starter-webflux en backend/PruebaTecnicaACGRJavaBackend/build.gradle, activando el stack reactivo para atender peticiones concurrentes y evitar bloqueos de hilos como ocurre en Spring MVC, lo que mejora la eficiencia del módulo financiero. <span class='reference'>Referencia: backend/PruebaTecnicaACGRJavaBackend/build.gradle</span>
¿Cómo se refleja la asincronía en los endpoints del controlador?|En backend/PruebaTecnicaACGRJavaBackend/src/main/java/com/acgr/sofka/pt/kardif/web/TransactionController.java los endpoints devuelven Flux<TransactionResponse> y Mono<TransactionResponse> delegando la lógica al servicio, por lo que la capa HTTP nunca bloquea hilos y mantiene el flujo reactivo. <span class='reference'>Referencia: backend/PruebaTecnicaACGRJavaBackend/src/main/java/com/acgr/sofka/pt/kardif/web/TransactionController.java</span>
¿Qué responsabilidad cumple TransactionController y por qué se mantiene delgado?|TransactionController valida el DTO y llama a TransactionService sin ejecutar reglas de negocio, cumpliendo el principio de responsabilidad única para que la capa web solo adapte HTTP. <span class='reference'>Referencia: backend/PruebaTecnicaACGRJavaBackend/src/main/java/com/acgr/sofka/pt/kardif/web/TransactionController.java</span>
¿Cómo se valida el monto entrante antes de procesarlo?|TransactionRequest define @NotNull y @DecimalMin, y el controlador lo recibe con @Valid, de modo que solo montos positivos y obligatorios alcanzan el flujo de negocio. <span class='reference'>Referencia: backend/PruebaTecnicaACGRJavaBackend/src/main/java/com/acgr/sofka/pt/kardif/service/dto/TransactionRequest.java</span>
¿Cuál es el papel de TransactionService?|TransactionService coordina la aplicación de reglas, la persistencia y la publicación de eventos sin tomar decisiones de transporte, manteniendo la lógica financiera centralizada. <span class='reference'>Referencia: backend/PruebaTecnicaACGRJavaBackend/src/main/java/com/acgr/sofka/pt/kardif/service/TransactionService.java</span>
¿Cómo opera el método registerTransaction en el servicio?|registerTransaction aplica una regla, crea un TransactionRecord, lo persiste con repository.save y publica un TransactionEvent mediante TransactionEventPublisher dentro de un pipeline reactivo para preservar la trazabilidad. <span class='reference'>Referencia: backend/PruebaTecnicaACGRJavaBackend/src/main/java/com/acgr/sofka/pt/kardif/service/TransactionService.java</span>
¿Cómo se consulta el historial de transacciones en el servicio?|getAllTransactions recorre repository.findAll(), recalcula la comisión usando applyRule y devuelve TransactionResponse, asegurando consistencia sin duplicar lógica. <span class='reference'>Referencia: backend/PruebaTecnicaACGRJavaBackend/src/main/java/com/acgr/sofka/pt/kardif/service/TransactionService.java</span>
¿Para qué sirve applyRule?|applyRule filtra el List<CommissionRule> y ejecuta matches y apply de la primera coincidencia, manteniendo la decisión de tasas desacoplada del servicio. <span class='reference'>Referencia: backend/PruebaTecnicaACGRJavaBackend/src/main/java/com/acgr/sofka/pt/kardif/service/TransactionService.java y backend/PruebaTecnicaACGRJavaBackend/src/main/java/com/acgr/sofka/pt/kardif/service/rules/CommissionRule.java</span>
¿Qué comportamientos define la interfaz CommissionRule?|CommissionRule expone únicamente matches y apply para mantener el contrato de reglas abierto a nuevas implementaciones sin tocar el servicio. <span class='reference'>Referencia: backend/PruebaTecnicaACGRJavaBackend/src/main/java/com/acgr/sofka/pt/kardif/service/rules/CommissionRule.java</span>
¿Qué encapsula ThresholdCommissionRule?|ThresholdCommissionRule guarda umbrales, la tasa y la plantilla de razón, calculando la comisión de forma precisa y centralizada para cumplir SRP. <span class='reference'>Referencia: backend/PruebaTecnicaACGRJavaBackend/src/main/java/com/acgr/sofka/pt/kardif/service/rules/ThresholdCommissionRule.java</span>
¿Cómo se configuran las reglas desde propiedades?|TransactionRulesConfiguration construye los beans de CommissionRule leyendo TransactionRulesProperties, permitiendo cambiar tasas y umbrales desde la configuración sin tocar código. <span class='reference'>Referencia: backend/PruebaTecnicaACGRJavaBackend/src/main/java/com/acgr/sofka/pt/kardif/config/TransactionRulesConfiguration.java</span>
¿Qué ocurre si no hay reglas definidas?|TransactionRulesConfiguration detecta la lista vacía y crea dos ThresholdCommissionRule con tasas del 2% y 5%, asegurando siempre un comportamiento definido. <span class='reference'>Referencia: backend/PruebaTecnicaACGRJavaBackend/src/main/java/com/acgr/sofka/pt/kardif/config/TransactionRulesConfiguration.java</span>
¿Qué hace TransactionRulesProperties?|TransactionRulesProperties expone el listado de RuleDefinition que el binder de Spring Boot llena desde transaction.rules, manteniendo la configuración centrada en datos. <span class='reference'>Referencia: backend/PruebaTecnicaACGRJavaBackend/src/main/java/com/acgr/sofka/pt/kardif/service/TransactionRulesProperties.java</span>
¿Qué campos incluye RuleDefinition?|Cada RuleDefinition tiene minAmount, maxAmount, rate y reasonTemplate, describiendo los límites sin lógica adicional para facilitar la evolución. <span class='reference'>Referencia: backend/PruebaTecnicaACGRJavaBackend/src/main/java/com/acgr/sofka/pt/kardif/service/TransactionRulesProperties.java</span>
¿Para qué sirve CommissionResult?|El record CommissionResult transporta la tasa aplicada, la comisión calculada y la razón, sirviendo como vínculo ligero entre regla y servicio. <span class='reference'>Referencia: backend/PruebaTecnicaACGRJavaBackend/src/main/java/com/acgr/sofka/pt/kardif/service/rules/CommissionResult.java</span>
¿Cómo se genera TransactionResponse?|TransactionResponse.from toma el TransactionRecord, la tasa y la razón para mapear el DTO final que se envia al cliente, usando @JsonFormat para el timestamp. <span class='reference'>Referencia: backend/PruebaTecnicaACGRJavaBackend/src/main/java/com/acgr/sofka/pt/kardif/service/dto/TransactionResponse.java</span>
¿Qué representa TransactionRecord?|TransactionRecord mapea la tabla transactions con @Table y @Column y expone getters/setters simples para que el mapeador R2DBC solo trate datos. <span class='reference'>Referencia: backend/PruebaTecnicaACGRJavaBackend/src/main/java/com/acgr/sofka/pt/kardif/domain/model/TransactionRecord.java</span>
¿Por qué extender ReactiveCrudRepository?|TransactionRepository hereda de ReactiveCrudRepository para recibir implementaciones reactivas de CRUD y mantener el flujo no bloqueante hasta la base de datos. <span class='reference'>Referencia: backend/PruebaTecnicaACGRJavaBackend/src/main/java/com/acgr/sofka/pt/kardif/domain/repository/TransactionRepository.java</span>
¿Cómo se configura la conexión R2DBC?|application.properties define spring.r2dbc.url=r2dbc:h2:mem:///commissiondb junto con usuario y contraseña vacíos, enlazando R2DBC con H2 en memoria. <span class='reference'>Referencia: backend/PruebaTecnicaACGRJavaBackend/src/main/resources/application.properties</span>
¿Para qué sirve schema.sql?|schema.sql crea la tabla transactions y se ejecuta en cada arranque gracias a spring.sql.init.mode=always para asegurar que la estructura exista. <span class='reference'>Referencia: backend/PruebaTecnicaACGRJavaBackend/src/main/resources/schema.sql</span>
¿Por qué se incluye data.sql?|data.sql permanece para permitir data seeds futuras y mantener coherencia con spring.sql.init.data-locations incluso si hoy solo tiene un comentario. <span class='reference'>Referencia: backend/PruebaTecnicaACGRJavaBackend/src/main/resources/data.sql</span>
¿Qué hace TransactionEventPublisher?|TransactionEventPublisher usa KafkaTemplate y Mono.create para publicar eventos sin bloquear, manteniendo la cadena reactiva después de persistir. <span class='reference'>Referencia: backend/PruebaTecnicaACGRJavaBackend/src/main/java/com/acgr/sofka/pt/kardif/messaging/TransactionEventPublisher.java</span>
¿Qué datos transporta TransactionEvent?|TransactionEvent incluye id, monto, comisión, tasa, razón y executedAt para entregar el mínimo que necesita cualquier consumidor Kafka. <span class='reference'>Referencia: backend/PruebaTecnicaACGRJavaBackend/src/main/java/com/acgr/sofka/pt/kardif/messaging/TransactionEvent.java</span>
¿Cómo se define el tópico Kafka?|La propiedad kardif.kafka.topic.transactions fija el nombre transactions para mantenerlo configurable desde application.properties. <span class='reference'>Referencia: backend/PruebaTecnicaACGRJavaBackend/src/main/resources/application.properties</span>
¿Por qué se usa JsonSerializer para Kafka?|spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer convierte TransactionEvent a JSON sin implementar serializadores manuales. <span class='reference'>Referencia: backend/PruebaTecnicaACGRJavaBackend/src/main/resources/application.properties</span>
¿Qué aporta springdoc-openapi-starter-webflux-ui?|Esa dependencia en build.gradle genera documentación Swagger sobre los endpoints reactivos para probar contratos con el jurado. <span class='reference'>Referencia: backend/PruebaTecnicaACGRJavaBackend/build.gradle</span>
¿Cómo se ajustan las rutas de la documentación?|application.properties asigna springdoc.api-docs.path=/api-docs y springdoc.swagger-ui.path=/swagger-ui/index.html para exponer la documentación en rutas conocidas. <span class='reference'>Referencia: backend/PruebaTecnicaACGRJavaBackend/src/main/resources/application.properties</span>
¿Qué asegura spring.sql.init.platform=h2 y mode=always?|Esas propiedades garantizan que Spring ejecute scripts compatibles con H2 en cada arranque, dejando la base lista para pruebas y demos. <span class='reference'>Referencia: backend/PruebaTecnicaACGRJavaBackend/src/main/resources/application.properties</span>
¿Por qué se registra LocalDateTime.now()?|TransactionService asigna LocalDateTime.now() al crear TransactionRecord para fijar el timestamp de ejecución y permitir trazabilidad temporal. <span class='reference'>Referencia: backend/PruebaTecnicaACGRJavaBackend/src/main/java/com/acgr/sofka/pt/kardif/service/TransactionService.java</span>
¿Cómo calcula la comisión ThresholdCommissionRule?|ThresholdCommissionRule multiplica el monto por la tasa y redondea a dos decimales, manteniendo el cálculo dentro de la regla para no dispersar la lógica. <span class='reference'>Referencia: backend/PruebaTecnicaACGRJavaBackend/src/main/java/com/acgr/sofka/pt/kardif/service/rules/ThresholdCommissionRule.java</span>
¿Por qué se usa BigDecimal?|BigDecimal se emplea en montos y tasas para evitar errores de punto flotante y mantener precisión financiera en los cálculos del servicio y las reglas. <span class='reference'>Referencia: backend/PruebaTecnicaACGRJavaBackend/src/main/java/com/acgr/sofka/pt/kardif/service/TransactionService.java</span>
¿Qué significa @Configuration(proxyBeanMethods = false)?|Esa anotación en TransactionRulesConfiguration evita proxies CGLIB innecesarios, acelerando el arranque ya que no hay llamadas entre beans. <span class='reference'>Referencia: backend/PruebaTecnicaACGRJavaBackend/src/main/java/com/acgr/sofka/pt/kardif/config/TransactionRulesConfiguration.java</span>
¿Qué dependencias se inyectan en TransactionService?|El constructor recibe TransactionRepository, List<CommissionRule> y TransactionEventPublisher para no depender de implementaciones concretas. <span class='reference'>Referencia: backend/PruebaTecnicaACGRJavaBackend/src/main/java/com/acgr/sofka/pt/kardif/service/TransactionService.java</span>
¿Qué sucede si applyRule no encuentra regla?|applyRule lanza IllegalStateException cuando ninguna regla aplica, detectando configuraciones incompletas en tiempo de ejecución. <span class='reference'>Referencia: backend/PruebaTecnicaACGRJavaBackend/src/main/java/com/acgr/sofka/pt/kardif/service/TransactionService.java</span>
¿Qué efecto tiene @ResponseStatus(HttpStatus.CREATED)?|El POST devuelve 201 al crear una transacción, alineándose con prácticas REST y clarificando que se generó un nuevo recurso. <span class='reference'>Referencia: backend/PruebaTecnicaACGRJavaBackend/src/main/java/com/acgr/sofka/pt/kardif/web/TransactionController.java</span>
¿Cómo respeta el controlador SRP?|El controlador solo adapta HTTP y delega la lógica al servicio, manteniendo la capa web enfocada en el transporte. <span class='reference'>Referencia: backend/PruebaTecnicaACGRJavaBackend/src/main/java/com/acgr/sofka/pt/kardif/web/TransactionController.java</span>
¿Por qué TransactionResponse usa @JsonFormat?|@JsonFormat en TransactionResponse garantiza un timestamp ISO que los clientes interpretan sin ambigüedad. <span class='reference'>Referencia: backend/PruebaTecnicaACGRJavaBackend/src/main/java/com/acgr/sofka/pt/kardif/service/dto/TransactionResponse.java</span>
¿Cómo se publica el evento sin bloquear el flujo?|TransactionEventPublisher.publish usa Mono.create y callbacks de KafkaTemplate para seguir la cadena reactiva y reportar entregas. <span class='reference'>Referencia: backend/PruebaTecnicaACGRJavaBackend/src/main/java/com/acgr/sofka/pt/kardif/messaging/TransactionEventPublisher.java</span>
¿Cómo se encadena la persistencia y la publicación?|TransactionService encadena repository.save().flatMap(...) y luego thenReturn para asegurarse de que la respuesta solo llegue cuando la publicación Kafka se completó. <span class='reference'>Referencia: backend/PruebaTecnicaACGRJavaBackend/src/main/java/com/acgr/sofka/pt/kardif/service/TransactionService.java</span>
¿Qué ventaja ofrece spring.kafka.bootstrap-servers con variable de entorno?|La propiedad spring.kafka.bootstrap-servers=${KAFKA_BOOTSTRAP_SERVERS:localhost:9092} permite apuntar a distintos clusters usando variables de entorno sin tocar código. <span class='reference'>Referencia: backend/PruebaTecnicaACGRJavaBackend/src/main/resources/application.properties</span>
¿Por qué incluir io.r2dbc:r2dbc-h2?|La dependencia io.r2dbc:r2dbc-h2 es el driver reactivo que habilita la comunicación no bloqueante con la base en memoria H2. <span class='reference'>Referencia: backend/PruebaTecnicaACGRJavaBackend/build.gradle</span>
¿Qué hace runtimeOnly com.h2database:h2?|runtimeOnly com.h2database:h2 incluye el motor H2 solo en tiempo de ejecución, evitando que se añada al classpath de compilación. <span class='reference'>Referencia: backend/PruebaTecnicaACGRJavaBackend/build.gradle</span>
¿Por qué spring.main.web-application-type=reactive?|Esa propiedad indica a Spring Boot que use WebFlux/Netty y no MVC, alineándose con las dependencias declaradas. <span class='reference'>Referencia: backend/PruebaTecnicaACGRJavaBackend/src/main/resources/application.properties</span>
¿Qué permite ReactiveCrudRepository?|ReactiveCrudRepository trae métodos reactivas como save y findAll, asegurando que el repositorio soporte Flux/Mono. <span class='reference'>Referencia: backend/PruebaTecnicaACGRJavaBackend/src/main/java/com/acgr/sofka/pt/kardif/domain/repository/TransactionRepository.java</span>
¿Por qué TransactionRecord mantiene getters y setters simples?|Los accesores sencillos permiten que R2DBC hidrate la entidad sin lógica adicional, conservando la claridad de la persistencia. <span class='reference'>Referencia: backend/PruebaTecnicaACGRJavaBackend/src/main/java/com/acgr/sofka/pt/kardif/domain/model/TransactionRecord.java</span>
¿Qué ventaja da usar record para DTOs?|TransactionRequest y TransactionResponse son record, lo que reduce boilerplate y refuerza inmutabilidad en los DTOs. <span class='reference'>Referencia: backend/PruebaTecnicaACGRJavaBackend/src/main/java/com/acgr/sofka/pt/kardif/service/dto/TransactionRequest.java y backend/PruebaTecnicaACGRJavaBackend/src/main/java/com/acgr/sofka/pt/kardif/service/dto/TransactionResponse.java</span>
¿Para qué sirve reasonTemplate?|reasonTemplate en application.properties define mensajes legibles sobre por qué se aplica cada tasa y se usa en ThresholdCommissionRule. <span class='reference'>Referencia: backend/PruebaTecnicaACGRJavaBackend/src/main/resources/application.properties</span>
¿Cómo parametrizan los umbrales los properties?|Las claves transaction.rules[0].max-amount y transaction.rules[1].min-amount permiten ajustar umbrales desde application.properties sin recompilar. <span class='reference'>Referencia: backend/PruebaTecnicaACGRJavaBackend/src/main/resources/application.properties</span>
¿Por qué spring.kafka.producer.key-serializer usa StringSerializer?|Definir org.apache.kafka.common.serialization.StringSerializer evita que Kafka intente serializar claves complejas, asegurando interoperabilidad. <span class='reference'>Referencia: backend/PruebaTecnicaACGRJavaBackend/src/main/resources/application.properties</span>
¿Qué aporta el tipado KafkaTemplate<String, TransactionEvent>?|Ese tipo asegura que solo se publiquen TransactionEvent con claves string y ayuda a detectar errores en compilación. <span class='reference'>Referencia: backend/PruebaTecnicaACGRJavaBackend/src/main/java/com/acgr/sofka/pt/kardif/messaging/TransactionEventPublisher.java</span>
¿Por qué AppComponent es standalone y cómo influye en la carga?|AppComponent es standalone y declara CommonModule y ReactiveFormsModule directamente para evitar NgModules adicionales, reduciendo la huella y permitiendo tree-shaking más efectivo en Angular 19 para acelerar el arranque. <span class='reference'>Referencia: frontend/prueba-tecnica-acgr-sofka-angular-ene2026/src/app/app.component.ts</span>
"""
